[package]
name = "normal2"
version = "0.1.0"
authors = ["Anonymous <anon@ymo.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.2.6"
ev3dev-lang-rust = "0.7.0"

